/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VaultHubPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  githubToken: "",
  defaultCategories: [],
  vaultHubUrl: "https://obsidianvaulthub.com",
  catalogRepoFullName: "Maws7140/vault-hub",
  publishedResources: [],
  publishDraft: null
};
var VaultHubSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Vault Hub Settings" });
    new import_obsidian.Setting(containerEl).setName("GitHub Personal Access Token").setDesc("Token used to create repos and push files. Requires 'repo' scope.").addText(
      (text) => text.setPlaceholder("ghp_xxxxxxxxxxxx").setValue(this.plugin.settings.githubToken).then((t) => {
        t.inputEl.type = "password";
        t.inputEl.style.width = "300px";
      }).onChange(async (value) => {
        this.plugin.settings.githubToken = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Vault Hub URL").setDesc("URL of the Vault Hub website.").addText(
      (text) => text.setPlaceholder("https://obsidianvaulthub.com").setValue(this.plugin.settings.vaultHubUrl).onChange(async (value) => {
        this.plugin.settings.vaultHubUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Catalog Repository").setDesc("Repo that stores the website catalog workflow. Used to request a refresh after publish/update.").addText(
      (text) => text.setPlaceholder("Maws7140/vault-hub").setValue(this.plugin.settings.catalogRepoFullName).onChange(async (value) => {
        this.plugin.settings.catalogRepoFullName = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Categories").setDesc("Comma-separated list of default categories for new publications.").addText(
      (text) => text.setPlaceholder("appearance, workflow").setValue(this.plugin.settings.defaultCategories.join(", ")).onChange(async (value) => {
        this.plugin.settings.defaultCategories = value.split(",").map((s) => s.trim()).filter((s) => s.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/modals/PublishModal.ts
var import_obsidian2 = require("obsidian");

// src/detection.ts
var MD_PATTERNS = [
  [/```dataviewjs/m, "dataview"],
  [/```dataview/m, "dataview"],
  [/```datacore/m, "datacore"],
  [/```tasks/m, "obsidian-tasks-plugin"],
  [/```kanban/m, "obsidian-kanban"],
  [/```excalidraw/m, "obsidian-excalidraw-plugin"],
  [/```chart/m, "obsidian-charts"],
  [/```cards-timeline/m, "any-block"],
  [/```button/m, "buttons"],
  [/```meta-bind/m, "obsidian-meta-bind-plugin"],
  [/`=\s*this\./m, "dataview"],
  [/`=\s*dv\./m, "dataview"],
  [/`\$=\s*dv\./m, "dataview"],
  [/<%\s*tp\./m, "templater-obsidian"],
  [/<%[-_*]?\s/m, "templater-obsidian"],
  [/kanban-plugin:/m, "obsidian-kanban"],
  [/^banner:/m, "obsidian-banners"]
];
var CSS_PATTERNS = [
  [/\.dataview/i, "dataview"],
  [/\.kanban/i, "obsidian-kanban"],
  [/\.tasks-plugin/i, "obsidian-tasks-plugin"],
  [/\.excalidraw/i, "obsidian-excalidraw-plugin"],
  [/\.cm-table-widget/i, "table-editor-obsidian"]
];
async function getInstalledPlugins(vault) {
  const plugins = [];
  const pluginsDir = `${vault.configDir}/plugins`;
  const listing = await vault.adapter.list(pluginsDir);
  for (const folder of listing.folders) {
    const manifestPath = `${folder}/manifest.json`;
    try {
      const raw = await vault.adapter.read(manifestPath);
      const manifest = JSON.parse(raw);
      plugins.push({
        id: manifest.id,
        name: manifest.name,
        version: manifest.version,
        author: manifest.author,
        autoDetected: false
      });
    } catch (e) {
    }
  }
  return plugins;
}
async function detectPlugins(fileContent, fileType, vault) {
  const installed = await getInstalledPlugins(vault);
  const installedIds = new Set(installed.map((p) => p.id));
  const detectedIds = /* @__PURE__ */ new Set();
  const patterns = fileType === "css" ? CSS_PATTERNS : MD_PATTERNS;
  for (const [regex, pluginId] of patterns) {
    if (regex.test(fileContent) && installedIds.has(pluginId)) {
      detectedIds.add(pluginId);
    }
  }
  return installed.map((p) => ({
    ...p,
    autoDetected: detectedIds.has(p.id)
  }));
}

// src/github.ts
var GitHubAPI = class {
  constructor(token) {
    this.token = token;
  }
  async request(path, options = {}) {
    const res = await fetch(`https://api.github.com${path}`, {
      ...options,
      headers: {
        Authorization: `token ${this.token}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
        ...options.headers
      }
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`GitHub API ${res.status}: ${body}`);
    }
    return res.json();
  }
  encodePath(path) {
    return path.split("/").map(encodeURIComponent).join("/");
  }
  async getUser() {
    return this.request("/user");
  }
  async createRepo(name, description) {
    return this.request("/user/repos", {
      method: "POST",
      body: JSON.stringify({
        name,
        description,
        auto_init: false,
        private: false
      })
    });
  }
  async addTopics(owner, repo, topics) {
    return this.request(`/repos/${owner}/${repo}/topics`, {
      method: "PUT",
      body: JSON.stringify({ names: topics })
    });
  }
  async createFile(owner, repo, path, content, message) {
    const encoded = btoa(unescape(encodeURIComponent(content)));
    return this.request(`/repos/${owner}/${repo}/contents/${this.encodePath(path)}`, {
      method: "PUT",
      body: JSON.stringify({ message, content: encoded })
    });
  }
  async createBinaryFile(owner, repo, path, base64Content, message) {
    return this.request(`/repos/${owner}/${repo}/contents/${this.encodePath(path)}`, {
      method: "PUT",
      body: JSON.stringify({ message, content: base64Content, encoding: "base64" })
    });
  }
  async updateFile(owner, repo, path, content, message, sha) {
    const encoded = btoa(unescape(encodeURIComponent(content)));
    return this.request(`/repos/${owner}/${repo}/contents/${this.encodePath(path)}`, {
      method: "PUT",
      body: JSON.stringify({ message, content: encoded, sha })
    });
  }
  async getFileContent(owner, repo, path) {
    try {
      const data = await this.request(
        `/repos/${owner}/${repo}/contents/${this.encodePath(path)}`
      );
      return { sha: data.sha, content: decodeURIComponent(escape(atob(data.content.replace(/\s/g, "")))) };
    } catch (error) {
      if (String(error).includes("GitHub API 404"))
        return null;
      throw error;
    }
  }
  async listFilesRecursive(owner, repo) {
    const data = await this.request(`/repos/${owner}/${repo}/git/trees/HEAD?recursive=1`);
    if (!Array.isArray(data.tree))
      return [];
    return data.tree.filter((item) => item.type === "blob").map((item) => ({
      path: item.path,
      sha: item.sha,
      download_url: `https://raw.githubusercontent.com/${owner}/${repo}/HEAD/${this.encodePath(item.path)}`,
      type: "file"
    }));
  }
  async fileExists(owner, repo, path) {
    return await this.getFileContent(owner, repo, path) !== null;
  }
  async getRepo(owner, repo) {
    return this.request(`/repos/${owner}/${repo}`);
  }
  async getAvailableRepoName(owner, baseName) {
    let candidate = baseName;
    let suffix = 2;
    while (true) {
      try {
        await this.getRepo(owner, candidate);
        candidate = `${baseName}-${suffix}`;
        suffix++;
      } catch (error) {
        if (String(error).includes("GitHub API 404"))
          return candidate;
        throw error;
      }
    }
  }
  async dispatchRepositoryEvent(owner, repo, eventType, clientPayload) {
    return this.request(`/repos/${owner}/${repo}/dispatches`, {
      method: "POST",
      body: JSON.stringify({
        event_type: eventType,
        client_payload: clientPayload || {}
      })
    });
  }
};

// src/hubmd.ts
function generateHubMd(data) {
  const lines = [];
  lines.push("---");
  lines.push("schema: 1");
  lines.push(`type: ${data.type}`);
  lines.push(`name: "${esc(data.name)}"`);
  lines.push(`tagline: "${esc(data.tagline)}"`);
  lines.push("description: |");
  data.description.split("\n").forEach((line) => lines.push(`  ${line}`));
  lines.push(`author: ${data.author}`);
  lines.push("categories:");
  data.categories.forEach((category) => lines.push(`  - ${category}`));
  if (data.tags.length > 0) {
    lines.push("tags:");
    data.tags.forEach((tag) => lines.push(`  - ${tag}`));
  }
  if (data.compatibleThemes.length > 0) {
    lines.push("compatible_themes:");
    data.compatibleThemes.forEach((theme) => lines.push(`  - ${theme}`));
  }
  if (data.screenshots.length > 0) {
    lines.push("screenshots:");
    data.screenshots.forEach((screenshot) => lines.push(`  - ${screenshot}`));
  }
  const selected = data.plugins.filter((plugin) => plugin.autoDetected);
  if (selected.length > 0) {
    lines.push("plugins:");
    selected.forEach((plugin) => {
      lines.push(`  - id: ${plugin.id}`);
      lines.push(`    name: "${esc(plugin.name)}"`);
      lines.push(`    version: "${esc(plugin.version)}"`);
    });
  }
  if (data.attachedSnippets.length > 0) {
    lines.push("attached_snippets:");
    data.attachedSnippets.forEach((snippet) => {
      lines.push(`  - path: "${esc(snippet.path)}"`);
      if (snippet.name)
        lines.push(`    name: "${esc(snippet.name)}"`);
      if (snippet.optional)
        lines.push("    optional: true");
    });
  }
  lines.push("environment:");
  lines.push(`  obsidian_version: "${esc(data.obsidianVersion)}"`);
  lines.push(`  theme: "${esc(data.theme)}"`);
  lines.push(`  os: "${esc(data.os)}"`);
  lines.push("files:");
  data.files.forEach((file) => {
    lines.push(`  - path: "${esc(file.path)}"`);
    lines.push(`    type: ${file.type}`);
    lines.push(`    size: ${file.size}`);
  });
  lines.push("---");
  lines.push("");
  lines.push(data.body.trim());
  lines.push("");
  return lines.join("\n");
}
function esc(value) {
  return String(value || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// src/readme.ts
function generateReadme(data) {
  var _a;
  const lines = [];
  lines.push(`# ${data.name}`);
  lines.push("");
  lines.push(data.tagline);
  lines.push("");
  lines.push("## Description");
  lines.push("");
  lines.push(data.description);
  lines.push("");
  const selected = data.plugins.filter((p) => p.autoDetected);
  const attachedSnippets = data.attachedSnippets || [];
  const screenshots = data.screenshots || [];
  if (selected.length > 0) {
    lines.push("## Required Plugins");
    lines.push("");
    lines.push("| Plugin | Version | Link |");
    lines.push("|--------|---------|------|");
    selected.forEach((p) => {
      lines.push(
        `| ${p.name} | ${p.version} | [GitHub](https://github.com/search?q=${encodeURIComponent(p.name + " obsidian")}) |`
      );
    });
    lines.push("");
  }
  if (attachedSnippets.length > 0) {
    lines.push("## Attached Snippets");
    lines.push("");
    attachedSnippets.forEach((snippet) => {
      lines.push(
        `- \`${snippet.path}\`${snippet.optional ? " (optional)" : ""}${snippet.name ? ` \u2014 ${snippet.name}` : ""}`
      );
    });
    lines.push("");
  }
  if (screenshots.length > 0) {
    lines.push("## Screenshots");
    lines.push("");
    screenshots.forEach((screenshot) => {
      const alt = screenshot.alt || screenshot.path.split("/").pop() || "Screenshot";
      lines.push(`![${alt}](${screenshot.path})`);
      lines.push("");
    });
  }
  lines.push("## Installation");
  lines.push("");
  if (data.type === "snippet") {
    lines.push(
      `1. Download \`${((_a = data.files[0]) == null ? void 0 : _a.path) || "snippet.css"}\` from this repo`
    );
    lines.push(
      "2. Place it in your vault's `.obsidian/snippets/` folder"
    );
    lines.push("3. Enable it in Settings > Appearance > CSS Snippets");
  } else if (data.type === "vault") {
    lines.push("1. Download or clone this repo");
    lines.push("2. Open the folder as an Obsidian vault");
    if (attachedSnippets.length > 0) {
      lines.push("3. Copy the attached CSS snippet files into `.obsidian/snippets/`");
      lines.push("4. Enable them in Settings > Appearance > CSS Snippets");
      if (selected.length > 0) {
        lines.push("5. Install or enable the required plugins listed above");
      }
    } else if (selected.length > 0) {
      lines.push("3. Install or enable the required plugins listed above");
    }
  } else {
    lines.push("1. Download the `.md` file(s) from this repo");
    lines.push("2. Place them in your vault");
    if (attachedSnippets.length > 0) {
      lines.push("3. Copy the attached CSS snippet files into `.obsidian/snippets/`");
      lines.push("4. Enable them in Settings > Appearance > CSS Snippets");
      if (selected.length > 0) {
        lines.push("5. Install the required plugins listed above");
      }
    } else if (selected.length > 0) {
      lines.push("3. Install the required plugins listed above");
    }
  }
  lines.push("");
  lines.push("---");
  lines.push("*Published via [Vault Hub](https://obsidianvaulthub.com)*");
  lines.push("");
  return lines.join("\n");
}
function syncReadmeScreenshots(readme, screenshots) {
  const normalized = readme.replace(/\r\n/g, "\n");
  const section = buildScreenshotSection(screenshots);
  const pattern = /## Screenshots\n\n[\s\S]*?(?=\n## |\n---\n|\s*$)/;
  if (section) {
    if (pattern.test(normalized)) {
      return normalized.replace(pattern, section.trimEnd());
    }
    const installHeading = "\n## Installation";
    if (normalized.includes(installHeading)) {
      return normalized.replace(installHeading, `
${section}${installHeading}`);
    }
    return `${normalized.trimEnd()}

${section}`;
  }
  if (pattern.test(normalized)) {
    return `${normalized.replace(pattern, "").replace(/\n{3,}/g, "\n\n").trimEnd()}
`;
  }
  return normalized;
}
function buildScreenshotSection(screenshots) {
  if (screenshots.length === 0)
    return "";
  const lines = ["## Screenshots", ""];
  screenshots.forEach((screenshot) => {
    const alt = screenshot.alt || screenshot.path.split("/").pop() || "Screenshot";
    lines.push(`![${alt}](${screenshot.path})`);
    lines.push("");
  });
  return `${lines.join("\n")}
`;
}

// src/modals/PublishModal.ts
function tfileToPublishFile(app, f) {
  return {
    path: f.path,
    name: f.name,
    extension: f.extension,
    size: f.stat.size,
    read: () => app.vault.read(f),
    readBinary: () => app.vault.adapter.readBinary(f.path)
  };
}
async function listSnippetFiles(app) {
  const adapter = app.vault.adapter;
  const dir = ".obsidian/snippets";
  try {
    const exists = await adapter.exists(dir);
    if (!exists)
      return [];
    const { files } = await adapter.list(dir);
    const cssFiles = files.filter((p) => p.toLowerCase().endsWith(".css"));
    return Promise.all(
      cssFiles.map(async (path) => {
        var _a;
        const name = path.split("/").pop() || path;
        let size = 0;
        try {
          const stat = await adapter.stat(path);
          size = (_a = stat == null ? void 0 : stat.size) != null ? _a : 0;
        } catch (e) {
        }
        return {
          path,
          name,
          extension: "css",
          size,
          read: () => adapter.read(path),
          readBinary: () => adapter.readBinary(path)
        };
      })
    );
  } catch (e) {
    return [];
  }
}
async function getEnabledSnippetIds(app) {
  try {
    const raw = await app.vault.adapter.read(`${app.vault.configDir}/appearance.json`);
    const parsed = JSON.parse(raw);
    return new Set((parsed.enabledCssSnippets || []).map((value) => String(value || "").toLowerCase()));
  } catch (e) {
    return /* @__PURE__ */ new Set();
  }
}
function snippetIdFromFile(file) {
  return file.name.replace(/\.css$/i, "").toLowerCase();
}
async function listImageFiles(app) {
  const imageExts = /* @__PURE__ */ new Set(["png", "jpg", "jpeg", "gif", "webp", "svg"]);
  return app.vault.getFiles().filter((f) => imageExts.has(f.extension.toLowerCase())).sort((a, b) => a.path.localeCompare(b.path)).map((f) => tfileToPublishFile(app, f));
}
function toBase64(data) {
  return Buffer.from(data).toString("base64");
}
var CATEGORIES = {
  snippet: [
    "ui-tweak",
    "layout",
    "typography",
    "colors",
    "editor",
    "sidebar",
    "dashboard",
    "starter",
    "ai"
  ],
  note: [
    "dashboard",
    "tracker",
    "query",
    "daily-note",
    "project-template",
    "kanban",
    "book-notes",
    "habit-tracker",
    "ai"
  ],
  bundle: [
    "starter",
    "student",
    "developer",
    "writer",
    "researcher",
    "ai",
    "pkm",
    "project-management",
    "worldbuilding",
    "journaling",
    "dashboard",
    "tracker",
    "finance"
  ]
};
var PublishModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.step = 1;
    // Step 1
    this.resourceType = "snippet";
    this.selectedFiles = [];
    this.selectedAttachedSnippets = [];
    this.selectedScreenshots = [];
    this.externalScreenshotUrls = "";
    this.fileSearchQuery = "";
    this.attachedSnippetSearchQuery = "";
    this.screenshotSearchQuery = "";
    // Step 2
    this.allPlugins = [];
    this.checkedPlugins = /* @__PURE__ */ new Set();
    // Step 3
    this.name = "";
    this.tagline = "";
    this.description = "";
    this.categories = [];
    this.tags = "";
    this.compatibleThemes = [];
    // Step 4
    this.readmeContent = "";
    this.pendingSelectedFilePaths = null;
    this.pendingAttachedSnippetPaths = null;
    this.pendingScreenshotPaths = null;
    this.restoredDraft = false;
    this.preserveDraftOnClose = true;
    this.plugin = plugin;
  }
  onOpen() {
    this.contentEl.empty();
    this.contentEl.createEl("p", { text: "Loading publish draft...", cls: "vault-hub-hint" });
    void this.initialize();
  }
  onClose() {
    if (this.preserveDraftOnClose) {
      void this.persistDraftOnClose();
    }
    this.contentEl.empty();
  }
  getPublishedType() {
    if (this.resourceType === "snippet")
      return "snippet";
    if (this.resourceType === "bundle")
      return "vault";
    return "note";
  }
  async initialize() {
    this.restoreDraft();
    await this.hydrateDraftSelections();
    this.renderStep();
  }
  restoreDraft() {
    const draft = this.plugin.settings.publishDraft;
    if (!draft)
      return;
    this.step = Math.min(Math.max(draft.step || 1, 1), 5);
    this.resourceType = draft.resourceType || "snippet";
    this.pendingSelectedFilePaths = [...draft.selectedFilePaths || []];
    this.pendingAttachedSnippetPaths = [...draft.attachedSnippetPaths || []];
    this.pendingScreenshotPaths = [...draft.screenshotPaths || []];
    this.externalScreenshotUrls = draft.externalScreenshotUrls || "";
    this.fileSearchQuery = draft.fileSearchQuery || "";
    this.attachedSnippetSearchQuery = draft.attachedSnippetSearchQuery || "";
    this.screenshotSearchQuery = draft.screenshotSearchQuery || "";
    this.checkedPlugins = new Set(draft.checkedPluginIds || []);
    this.name = draft.name || "";
    this.tagline = draft.tagline || "";
    this.description = draft.description || "";
    this.categories = [...draft.categories || []];
    this.tags = draft.tags || "";
    this.compatibleThemes = [...draft.compatibleThemes || []];
    this.readmeContent = draft.readmeContent || "";
    this.restoredDraft = true;
  }
  async persistDraftOnClose() {
    if (!this.hasDraftContent()) {
      if (this.plugin.settings.publishDraft) {
        this.plugin.settings.publishDraft = null;
        await this.plugin.saveSettings();
      }
      return;
    }
    await this.saveDraft();
  }
  async hydrateDraftSelections() {
    if (this.pendingSelectedFilePaths) {
      const files = await this.collectCandidateFiles();
      this.restoreSelectionFromPaths(files, this.pendingSelectedFilePaths, (restored) => {
        this.selectedFiles = restored;
        this.pendingSelectedFilePaths = null;
      });
    }
    if ((this.resourceType === "note" || this.resourceType === "bundle") && this.pendingAttachedSnippetPaths) {
      const snippetFiles = await listSnippetFiles(this.app);
      this.restoreSelectionFromPaths(
        snippetFiles,
        this.pendingAttachedSnippetPaths,
        (restored) => {
          this.selectedAttachedSnippets = restored;
          this.pendingAttachedSnippetPaths = null;
        }
      );
    }
    if (this.pendingScreenshotPaths) {
      const imageFiles = await listImageFiles(this.app);
      this.restoreSelectionFromPaths(imageFiles, this.pendingScreenshotPaths, (restored) => {
        this.selectedScreenshots = restored;
        this.pendingScreenshotPaths = null;
      });
    }
  }
  hasDraftContent() {
    var _a, _b, _c;
    return this.step > 1 || this.selectedFiles.length > 0 || this.selectedAttachedSnippets.length > 0 || this.selectedScreenshots.length > 0 || (((_a = this.pendingSelectedFilePaths) == null ? void 0 : _a.length) || 0) > 0 || (((_b = this.pendingAttachedSnippetPaths) == null ? void 0 : _b.length) || 0) > 0 || (((_c = this.pendingScreenshotPaths) == null ? void 0 : _c.length) || 0) > 0 || this.externalScreenshotUrls.trim().length > 0 || this.name.trim().length > 0 || this.tagline.trim().length > 0 || this.description.trim().length > 0 || this.categories.length > 0 || this.tags.trim().length > 0 || this.compatibleThemes.length > 0 || this.readmeContent.trim().length > 0;
  }
  buildDraft() {
    return {
      step: this.step,
      resourceType: this.resourceType,
      selectedFilePaths: this.selectedFiles.length > 0 ? this.selectedFiles.map((file) => file.path) : [...this.pendingSelectedFilePaths || []],
      attachedSnippetPaths: this.selectedAttachedSnippets.length > 0 ? this.selectedAttachedSnippets.map((file) => file.path) : [...this.pendingAttachedSnippetPaths || []],
      screenshotPaths: this.selectedScreenshots.length > 0 ? this.selectedScreenshots.map((file) => file.path) : [...this.pendingScreenshotPaths || []],
      externalScreenshotUrls: this.externalScreenshotUrls,
      fileSearchQuery: this.fileSearchQuery,
      attachedSnippetSearchQuery: this.attachedSnippetSearchQuery,
      screenshotSearchQuery: this.screenshotSearchQuery,
      checkedPluginIds: [...this.checkedPlugins],
      name: this.name,
      tagline: this.tagline,
      description: this.description,
      categories: [...this.categories],
      tags: this.tags,
      compatibleThemes: [...this.compatibleThemes],
      readmeContent: this.readmeContent
    };
  }
  async saveDraft() {
    this.plugin.settings.publishDraft = this.buildDraft();
    await this.plugin.saveSettings();
  }
  async discardDraft() {
    this.plugin.settings.publishDraft = null;
    await this.plugin.saveSettings();
  }
  resetState() {
    this.step = 1;
    this.resourceType = "snippet";
    this.selectedFiles = [];
    this.selectedAttachedSnippets = [];
    this.selectedScreenshots = [];
    this.externalScreenshotUrls = "";
    this.fileSearchQuery = "";
    this.attachedSnippetSearchQuery = "";
    this.screenshotSearchQuery = "";
    this.allPlugins = [];
    this.checkedPlugins = /* @__PURE__ */ new Set();
    this.name = "";
    this.tagline = "";
    this.description = "";
    this.categories = [];
    this.tags = "";
    this.compatibleThemes = [];
    this.readmeContent = "";
    this.pendingSelectedFilePaths = null;
    this.pendingAttachedSnippetPaths = null;
    this.pendingScreenshotPaths = null;
    this.restoredDraft = false;
  }
  restoreSelectionFromPaths(files, pendingPaths, assign) {
    if (!pendingPaths)
      return;
    const wanted = new Set(pendingPaths);
    assign(files.filter((file) => wanted.has(file.path)));
  }
  renderStep() {
    this.contentEl.empty();
    this.contentEl.addClass("vault-hub-modal");
    const header = this.contentEl.createDiv("vault-hub-header");
    header.createEl("h2", { text: `Publish Resource \u2014 Step ${this.step} of 5` });
    const progress = header.createDiv("vault-hub-progress");
    for (let i = 1; i <= 5; i++) {
      const dot = progress.createSpan("vault-hub-dot");
      if (i === this.step)
        dot.addClass("active");
      else if (i < this.step)
        dot.addClass("done");
    }
    if (this.restoredDraft) {
      const draftBar = this.contentEl.createDiv("vault-hub-hint");
      draftBar.setText("Restored your saved publish draft.");
      const discardBtn = draftBar.createEl("button", { text: "Start over" });
      discardBtn.type = "button";
      discardBtn.style.marginLeft = "8px";
      discardBtn.addEventListener("click", async () => {
        this.resetState();
        await this.discardDraft();
        this.renderStep();
      });
    }
    switch (this.step) {
      case 1:
        this.renderStep1();
        break;
      case 2:
        this.renderStep2();
        break;
      case 3:
        this.renderStep3();
        break;
      case 4:
        this.renderStep4();
        break;
      case 5:
        this.renderStep5();
        break;
    }
  }
  async renderStep1() {
    const c = this.contentEl;
    new import_obsidian2.Setting(c).setName("Resource Type").addDropdown((dd) => {
      dd.addOption("snippet", "CSS Snippet");
      dd.addOption("note", "Note / Template / Dashboard");
      dd.addOption("bundle", "Vault / Multi-file Template");
      dd.setValue(this.resourceType);
      dd.onChange((v) => {
        this.resourceType = v;
        this.selectedFiles = [];
        this.selectedAttachedSnippets = [];
        this.checkedPlugins = /* @__PURE__ */ new Set();
        this.allPlugins = [];
        this.pendingSelectedFilePaths = null;
        this.pendingAttachedSnippetPaths = null;
        this.renderStep();
      });
    });
    const files = await this.collectCandidateFiles();
    const availableSnippets = this.resourceType === "note" ? await listSnippetFiles(this.app) : [];
    this.restoreSelectionFromPaths(files, this.pendingSelectedFilePaths, (restored) => {
      this.selectedFiles = restored;
      this.pendingSelectedFilePaths = null;
    });
    if (this.resourceType === "note") {
      this.restoreSelectionFromPaths(
        availableSnippets,
        this.pendingAttachedSnippetPaths,
        (restored) => {
          this.selectedAttachedSnippets = restored;
          this.pendingAttachedSnippetPaths = null;
        }
      );
    }
    const fileSection = c.createDiv();
    const isBundle = this.resourceType === "bundle";
    fileSection.createEl("h4", { text: `Select file${isBundle ? "s" : ""}` });
    const fileSearch = fileSection.createEl("input", {
      type: "text",
      placeholder: "Search files...",
      cls: "vault-hub-search-input"
    });
    fileSearch.value = this.fileSearchQuery;
    fileSearch.addEventListener("input", () => {
      this.fileSearchQuery = fileSearch.value;
      renderFileList();
    });
    if (this.resourceType === "snippet") {
      fileSection.createEl("p", {
        text: "Sourced from .obsidian/snippets. Drop .css files there if nothing shows up.",
        cls: "vault-hub-hint"
      });
    }
    if (files.length === 0) {
      fileSection.createEl("p", {
        text: this.resourceType === "snippet" ? "No CSS snippets found in .obsidian/snippets." : this.resourceType === "bundle" ? "No markdown files found in this vault." : "No markdown files found in this vault.",
        cls: "vault-hub-hint"
      });
    }
    let count = null;
    if (isBundle && files.length > 0) {
      const bulk = fileSection.createDiv("vault-hub-bulk");
      const selectAll = bulk.createEl("button", { text: "Select all" });
      selectAll.type = "button";
      selectAll.addEventListener("click", () => {
        this.selectedFiles = files.slice();
        renderFileList();
      });
      const clearAll = bulk.createEl("button", { text: "Clear" });
      clearAll.type = "button";
      clearAll.addEventListener("click", () => {
        this.selectedFiles = [];
        renderFileList();
      });
      count = bulk.createSpan({ cls: "vault-hub-bulk-count" });
    }
    const list = fileSection.createDiv("vault-hub-file-list");
    const emptyFileSearch = fileSection.createEl("p", {
      text: "No files match that search.",
      cls: "vault-hub-hint"
    });
    emptyFileSearch.style.display = "none";
    const renderFileList = () => {
      const fileSearchNeedle = this.fileSearchQuery.trim().toLowerCase();
      const visibleFiles = fileSearchNeedle ? files.filter((file) => file.path.toLowerCase().includes(fileSearchNeedle)) : files;
      const selectedPaths = new Set(this.selectedFiles.map((f) => f.path));
      list.empty();
      emptyFileSearch.style.display = files.length > 0 && visibleFiles.length === 0 ? "" : "none";
      if (count) {
        count.setText(`${this.selectedFiles.length} / ${files.length} selected`);
      }
      visibleFiles.forEach((f) => {
        const row = list.createDiv("vault-hub-file-row");
        const cb = row.createEl("input", { type: isBundle ? "checkbox" : "radio" });
        cb.name = "vault-hub-file";
        cb.checked = selectedPaths.has(f.path);
        cb.addEventListener("change", () => {
          if (isBundle) {
            if (cb.checked)
              this.selectedFiles.push(f);
            else
              this.selectedFiles = this.selectedFiles.filter((x) => x.path !== f.path);
          } else {
            this.selectedFiles = cb.checked ? [f] : [];
          }
          if (count) {
            count.setText(`${this.selectedFiles.length} / ${files.length} selected`);
          }
        });
        row.createSpan({ text: f.path });
      });
    };
    renderFileList();
    if (this.resourceType === "note") {
      const snippetSection = c.createDiv();
      snippetSection.createEl("h4", { text: "Attach CSS snippets" });
      snippetSection.createEl("p", {
        text: "Optional. These will be uploaded into the repo and listed in hub.md so install can pull them automatically.",
        cls: "vault-hub-hint"
      });
      const filterSnippets = () => {
        const needle = this.attachedSnippetSearchQuery.trim().toLowerCase();
        if (!needle)
          return availableSnippets;
        return availableSnippets.filter((file) => {
          const haystack = `${file.name} ${file.path}`.toLowerCase();
          return haystack.includes(needle);
        });
      };
      const attachedSnippetSearch = snippetSection.createEl("input", {
        type: "text",
        placeholder: "Search snippets...",
        cls: "vault-hub-search-input"
      });
      attachedSnippetSearch.value = this.attachedSnippetSearchQuery;
      if (availableSnippets.length === 0) {
        snippetSection.createEl("p", {
          text: "No CSS snippets found in .obsidian/snippets.",
          cls: "vault-hub-hint"
        });
      } else {
        const snippetList = snippetSection.createDiv("vault-hub-file-list");
        const emptySnippetSearch = snippetSection.createEl("p", {
          text: "No snippets match that search.",
          cls: "vault-hub-hint"
        });
        emptySnippetSearch.style.display = "none";
        const renderSnippetList = () => {
          const visibleSnippets = filterSnippets();
          const selectedSnippetPaths = new Set(this.selectedAttachedSnippets.map((f) => f.path));
          snippetList.empty();
          emptySnippetSearch.style.display = visibleSnippets.length === 0 ? "" : "none";
          visibleSnippets.forEach((file) => {
            const row = snippetList.createDiv("vault-hub-file-row");
            const cb = row.createEl("input", { type: "checkbox" });
            cb.checked = selectedSnippetPaths.has(file.path);
            cb.addEventListener("change", () => {
              if (cb.checked)
                this.selectedAttachedSnippets.push(file);
              else
                this.selectedAttachedSnippets = this.selectedAttachedSnippets.filter((x) => x.path !== file.path);
            });
            row.createSpan({ text: file.path });
          });
        };
        attachedSnippetSearch.addEventListener("input", () => {
          this.attachedSnippetSearchQuery = attachedSnippetSearch.value;
          renderSnippetList();
        });
        renderSnippetList();
      }
    }
    this.addNav(c, null, () => {
      if (this.selectedFiles.length === 0) {
        new import_obsidian2.Notice("Select at least one file");
        return false;
      }
      return true;
    });
  }
  async collectCandidateFiles() {
    if (this.resourceType === "snippet") {
      const snippets = await listSnippetFiles(this.app);
      return snippets.sort((a, b) => a.path.localeCompare(b.path));
    }
    return this.app.vault.getFiles().filter((f) => f.extension === "md").sort((a, b) => a.path.localeCompare(b.path)).map((f) => tfileToPublishFile(this.app, f));
  }
  async renderStep2() {
    const c = this.contentEl;
    c.createEl("h4", { text: "Select Required Plugins" });
    c.createEl("p", {
      text: "Auto-detected plugins are pre-checked. Review and adjust.",
      cls: "vault-hub-hint"
    });
    const loading = c.createDiv({ text: "Scanning..." });
    const fileType = this.resourceType === "snippet" ? "css" : "md";
    const detectedById = /* @__PURE__ */ new Map();
    for (const file of this.selectedFiles) {
      const content = await file.read();
      const detected = await detectPlugins(content, fileType, this.app.vault);
      detected.forEach((plugin) => detectedById.set(plugin.id, plugin));
    }
    this.allPlugins = [...detectedById.values()];
    loading.remove();
    if (this.checkedPlugins.size === 0) {
      this.allPlugins.forEach((p) => {
        if (p.autoDetected)
          this.checkedPlugins.add(p.id);
      });
    }
    if (this.allPlugins.length > 0) {
      const bulk = c.createDiv("vault-hub-bulk");
      const selectAll = bulk.createEl("button", { text: "Select all" });
      selectAll.type = "button";
      selectAll.addEventListener("click", () => {
        this.allPlugins.forEach((plugin) => this.checkedPlugins.add(plugin.id));
        renderPluginList();
      });
      const clearAll = bulk.createEl("button", { text: "Clear" });
      clearAll.type = "button";
      clearAll.addEventListener("click", () => {
        this.checkedPlugins.clear();
        renderPluginList();
      });
      const count = bulk.createSpan({ cls: "vault-hub-bulk-count" });
      const updateCount = () => {
        count.setText(`${this.checkedPlugins.size} / ${this.allPlugins.length} selected`);
      };
      const list = c.createDiv("vault-hub-plugin-list");
      const renderPluginList = () => {
        list.empty();
        updateCount();
        this.allPlugins.forEach((p) => {
          const row = list.createDiv("vault-hub-plugin-row");
          const cb = row.createEl("input", { type: "checkbox" });
          cb.checked = this.checkedPlugins.has(p.id);
          cb.addEventListener("change", () => {
            if (cb.checked)
              this.checkedPlugins.add(p.id);
            else
              this.checkedPlugins.delete(p.id);
            updateCount();
          });
          const info = row.createDiv("vault-hub-plugin-info");
          info.createSpan({ text: p.name, cls: "vault-hub-plugin-name" });
          info.createSpan({ text: ` v${p.version}`, cls: "vault-hub-plugin-version" });
          if (p.autoDetected) {
            info.createSpan({ text: " (auto-detected)", cls: "vault-hub-auto-badge" });
          }
        });
      };
      renderPluginList();
    }
    if (this.allPlugins.length === 0) {
      c.createEl("p", { text: "No community plugins installed.", cls: "vault-hub-hint" });
    }
    if (this.resourceType === "bundle") {
      const snippetSection = c.createDiv();
      snippetSection.createEl("h4", { text: "Attach active CSS snippets" });
      snippetSection.createEl("p", {
        text: "Enabled snippets are preselected. Review the list and keep only the ones this vault actually needs.",
        cls: "vault-hub-hint"
      });
      const availableSnippets = await listSnippetFiles(this.app);
      const enabledSnippetIds = await getEnabledSnippetIds(this.app);
      if (!this.pendingAttachedSnippetPaths && this.selectedAttachedSnippets.length === 0 && enabledSnippetIds.size > 0) {
        this.selectedAttachedSnippets = availableSnippets.filter(
          (file) => enabledSnippetIds.has(snippetIdFromFile(file))
        );
      }
      const snippetSearch = snippetSection.createEl("input", {
        type: "text",
        placeholder: "Search snippets...",
        cls: "vault-hub-search-input"
      });
      snippetSearch.value = this.attachedSnippetSearchQuery;
      if (availableSnippets.length === 0) {
        snippetSection.createEl("p", {
          text: "No CSS snippets found in .obsidian/snippets.",
          cls: "vault-hub-hint"
        });
      } else {
        const bulk = snippetSection.createDiv("vault-hub-bulk");
        const selectAll = bulk.createEl("button", { text: "Select all" });
        selectAll.type = "button";
        const selectEnabled = bulk.createEl("button", { text: "Select enabled" });
        selectEnabled.type = "button";
        const clearAll = bulk.createEl("button", { text: "Clear" });
        clearAll.type = "button";
        const count = bulk.createSpan({ cls: "vault-hub-bulk-count" });
        const snippetList = snippetSection.createDiv("vault-hub-file-list");
        const emptySnippetSearch = snippetSection.createEl("p", {
          text: "No snippets match that search.",
          cls: "vault-hub-hint"
        });
        emptySnippetSearch.style.display = "none";
        const renderBundleSnippetList = () => {
          const needle = this.attachedSnippetSearchQuery.trim().toLowerCase();
          const visibleSnippets = needle ? availableSnippets.filter((file) => `${file.name} ${file.path}`.toLowerCase().includes(needle)) : availableSnippets;
          const selectedSnippetPaths = new Set(this.selectedAttachedSnippets.map((file) => file.path));
          snippetList.empty();
          emptySnippetSearch.style.display = visibleSnippets.length === 0 ? "" : "none";
          count.setText(`${this.selectedAttachedSnippets.length} / ${availableSnippets.length} selected`);
          visibleSnippets.forEach((file) => {
            const row = snippetList.createDiv("vault-hub-file-row");
            const cb = row.createEl("input", { type: "checkbox" });
            cb.checked = selectedSnippetPaths.has(file.path);
            cb.addEventListener("change", () => {
              if (cb.checked) {
                if (!this.selectedAttachedSnippets.some((value) => value.path === file.path)) {
                  this.selectedAttachedSnippets.push(file);
                }
              } else {
                this.selectedAttachedSnippets = this.selectedAttachedSnippets.filter((x) => x.path !== file.path);
              }
              count.setText(`${this.selectedAttachedSnippets.length} / ${availableSnippets.length} selected`);
            });
            const label = row.createDiv("vault-hub-plugin-info");
            label.createSpan({ text: file.path, cls: "vault-hub-plugin-name" });
            if (enabledSnippetIds.has(snippetIdFromFile(file))) {
              label.createSpan({ text: " (enabled)", cls: "vault-hub-auto-badge" });
            }
          });
        };
        selectAll.addEventListener("click", () => {
          this.selectedAttachedSnippets = availableSnippets.slice();
          renderBundleSnippetList();
        });
        selectEnabled.addEventListener("click", () => {
          this.selectedAttachedSnippets = availableSnippets.filter(
            (file) => enabledSnippetIds.has(snippetIdFromFile(file))
          );
          renderBundleSnippetList();
        });
        clearAll.addEventListener("click", () => {
          this.selectedAttachedSnippets = [];
          renderBundleSnippetList();
        });
        snippetSearch.addEventListener("input", () => {
          this.attachedSnippetSearchQuery = snippetSearch.value;
          renderBundleSnippetList();
        });
        renderBundleSnippetList();
      }
    }
    this.addNav(c, null, null);
  }
  renderStep3() {
    const c = this.contentEl;
    new import_obsidian2.Setting(c).setName("Name").addText((t) => {
      t.setPlaceholder("My Resource").setValue(this.name);
      t.onChange((v) => this.name = v);
      t.inputEl.style.width = "100%";
    });
    new import_obsidian2.Setting(c).setName("Tagline").setDesc("One-line summary").addText((t) => {
      t.setPlaceholder("A brief description").setValue(this.tagline);
      t.onChange((v) => this.tagline = v);
      t.inputEl.style.width = "100%";
    });
    new import_obsidian2.Setting(c).setName("Description").addTextArea((t) => {
      t.setPlaceholder("Detailed description...").setValue(this.description);
      t.onChange((v) => this.description = v);
      t.inputEl.style.width = "100%";
      t.inputEl.style.minHeight = "80px";
    });
    const cats = CATEGORIES[this.resourceType] || [];
    const categorySetting = new import_obsidian2.Setting(c).setName("Categories").setDesc("Pick one or more.");
    const categoryControl = categorySetting.controlEl.createDiv("vault-hub-multi-select");
    const categoryBulk = categoryControl.createDiv("vault-hub-bulk");
    const selectAllCategories = categoryBulk.createEl("button", { text: "Select all" });
    selectAllCategories.type = "button";
    selectAllCategories.addEventListener("click", () => {
      this.categories = [...cats];
      renderCategoryList();
    });
    const clearCategories = categoryBulk.createEl("button", { text: "Clear" });
    clearCategories.type = "button";
    clearCategories.addEventListener("click", () => {
      this.categories = [];
      renderCategoryList();
    });
    const categoryCount = categoryBulk.createSpan({ cls: "vault-hub-bulk-count" });
    const categoryList = categoryControl.createDiv("vault-hub-checkbox-grid");
    const renderCategoryList = () => {
      categoryList.empty();
      const selected = new Set(this.categories);
      categoryCount.setText(`${selected.size} / ${cats.length} selected`);
      cats.forEach((cat) => {
        const row = categoryList.createEl("label", { cls: "vault-hub-checkbox-row" });
        const cb = row.createEl("input", { type: "checkbox" });
        cb.checked = selected.has(cat);
        cb.addEventListener("change", () => {
          if (cb.checked) {
            if (!this.categories.includes(cat))
              this.categories.push(cat);
          } else {
            this.categories = this.categories.filter((value) => value !== cat);
          }
          categoryCount.setText(`${this.categories.length} / ${cats.length} selected`);
        });
        row.createSpan({ text: cat });
      });
    };
    renderCategoryList();
    new import_obsidian2.Setting(c).setName("Tags").setDesc("Comma-separated").addText((t) => {
      t.setPlaceholder("glass, blur, dark").setValue(this.tags);
      t.onChange((v) => this.tags = v);
    });
    const screenshotSection = c.createDiv();
    screenshotSection.createEl("h4", { text: "Screenshots" });
    screenshotSection.createEl("p", {
      text: "Optional. Use local image files, external image URLs, or both.",
      cls: "vault-hub-hint"
    });
    new import_obsidian2.Setting(screenshotSection).setName("External screenshot URLs").setDesc("One per line. Direct image URLs work best.").addTextArea((t) => {
      t.setPlaceholder("https://example.com/screenshot.png").setValue(this.externalScreenshotUrls);
      t.onChange((v) => this.externalScreenshotUrls = v);
      t.inputEl.style.width = "100%";
      t.inputEl.style.minHeight = "72px";
    });
    const screenshotSearch = screenshotSection.createEl("input", {
      type: "text",
      placeholder: "Search images...",
      cls: "vault-hub-search-input"
    });
    screenshotSearch.value = this.screenshotSearchQuery;
    const screenshotList = screenshotSection.createDiv("vault-hub-file-list");
    const screenshotEmpty = screenshotSection.createEl("p", {
      text: "No screenshots match that search.",
      cls: "vault-hub-hint"
    });
    screenshotEmpty.style.display = "none";
    const renderScreenshotList = async () => {
      const allImages = await listImageFiles(this.app);
      this.restoreSelectionFromPaths(allImages, this.pendingScreenshotPaths, (restored) => {
        this.selectedScreenshots = restored;
        this.pendingScreenshotPaths = null;
      });
      const needle = this.screenshotSearchQuery.trim().toLowerCase();
      const visibleImages = needle ? allImages.filter((file) => file.path.toLowerCase().includes(needle)) : allImages;
      const selectedImagePaths = new Set(this.selectedScreenshots.map((file) => file.path));
      screenshotList.empty();
      screenshotEmpty.style.display = allImages.length > 0 && visibleImages.length === 0 ? "" : "none";
      if (allImages.length === 0) {
        screenshotList.createEl("p", {
          text: "No image files found in this vault.",
          cls: "vault-hub-hint"
        });
        return;
      }
      visibleImages.forEach((file) => {
        const row = screenshotList.createDiv("vault-hub-file-row");
        const cb = row.createEl("input", { type: "checkbox" });
        cb.checked = selectedImagePaths.has(file.path);
        cb.addEventListener("change", () => {
          if (cb.checked)
            this.selectedScreenshots.push(file);
          else
            this.selectedScreenshots = this.selectedScreenshots.filter((x) => x.path !== file.path);
        });
        row.createSpan({ text: file.path });
      });
    };
    screenshotSearch.addEventListener("input", () => {
      this.screenshotSearchQuery = screenshotSearch.value;
      void renderScreenshotList();
    });
    void renderScreenshotList();
    if (this.resourceType === "snippet") {
      new import_obsidian2.Setting(c).setName("Compatible Themes").addDropdown((dd) => {
        dd.addOption("any", "Any theme");
        ["minimal", "velocity", "obsidian-default", "catppuccin"].forEach(
          (t) => dd.addOption(t, t)
        );
        dd.setValue(this.compatibleThemes[0] || "any");
        dd.onChange((v) => this.compatibleThemes = [v]);
      });
    }
    this.addNav(c, null, () => {
      if (!this.name.trim()) {
        new import_obsidian2.Notice("Name is required");
        return false;
      }
      this.readmeContent = generateReadme(this.buildReadmeData());
      return true;
    });
  }
  renderStep4() {
    const c = this.contentEl;
    c.createEl("h4", { text: "Edit README" });
    c.createEl("p", {
      text: "Auto-generated from your details. Edit freely.",
      cls: "vault-hub-hint"
    });
    const textarea = c.createEl("textarea", { cls: "vault-hub-readme-editor" });
    textarea.value = this.readmeContent;
    textarea.addEventListener("input", () => {
      this.readmeContent = textarea.value;
    });
    this.addNav(c, null, null);
  }
  renderStep5() {
    const c = this.contentEl;
    c.createEl("h4", { text: "Review & Publish" });
    const publishedType = this.getPublishedType();
    const summary = c.createDiv("vault-hub-summary");
    summary.createEl("p", { text: `Type: ${publishedType}${this.resourceType === "bundle" ? " (multi-file)" : ""}` });
    summary.createEl("p", { text: `Name: ${this.name}` });
    summary.createEl("p", { text: `Files: ${this.selectedFiles.map((f) => f.path).join(", ")}` });
    if (this.selectedAttachedSnippets.length > 0) {
      summary.createEl("p", {
        text: `Attached snippets: ${this.selectedAttachedSnippets.map((f) => f.name).join(", ")}`
      });
    }
    if (this.selectedScreenshots.length > 0) {
      summary.createEl("p", {
        text: `Screenshots: ${this.selectedScreenshots.map((f) => f.name).join(", ")}`
      });
    }
    const externalScreenshotUrls = this.getExternalScreenshotUrls();
    if (externalScreenshotUrls.length > 0) {
      summary.createEl("p", {
        text: `External screenshots: ${externalScreenshotUrls.length}`
      });
    }
    const selPlugins = this.allPlugins.filter((p) => this.checkedPlugins.has(p.id));
    summary.createEl("p", {
      text: `Plugins: ${selPlugins.length > 0 ? selPlugins.map((p) => p.name).join(", ") : "None"}`
    });
    summary.createEl("p", { text: `Categories: ${this.categories.join(", ") || "None"}` });
    const btnContainer = c.createDiv("vault-hub-nav");
    const backBtn = btnContainer.createEl("button", { text: "Back" });
    backBtn.addEventListener("click", async () => {
      this.step--;
      await this.saveDraft();
      this.renderStep();
    });
    const publishBtn = btnContainer.createEl("button", {
      text: "Publish",
      cls: "mod-cta"
    });
    publishBtn.addEventListener("click", () => this.doPublish());
  }
  async doPublish() {
    var _a;
    const token = this.plugin.settings.githubToken;
    if (!token) {
      new import_obsidian2.Notice("Set your GitHub token in Vault Hub settings first");
      return;
    }
    const c = this.contentEl;
    c.empty();
    c.createEl("h3", { text: "Publishing..." });
    const status = c.createEl("p", { text: "Creating repository..." });
    try {
      await this.saveDraft();
      const gh = new GitHubAPI(token);
      const user = await gh.getUser();
      const publishedType = this.getPublishedType();
      const slug = this.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "resource";
      const repoName = await gh.getAvailableRepoName(user.login, `obsidian-${publishedType}-${slug}`);
      status.setText("Creating repository...");
      const repo = await gh.createRepo(repoName, this.tagline || this.name);
      const [owner, rName] = repo.full_name.split("/");
      const topicMap = {
        vault: "obsidian-vault-template",
        snippet: "obsidian-css-snippet",
        note: "obsidian-note-template"
      };
      status.setText("Adding topic tag...");
      await gh.addTopics(owner, rName, [topicMap[publishedType]]);
      for (const file of this.selectedFiles) {
        status.setText(`Uploading ${file.path}...`);
        const content = await file.read();
        await gh.createFile(owner, rName, file.path, content, `Add ${file.path}`);
      }
      const attachedSnippetFiles = this.getAttachedSnippetFiles();
      for (const file of attachedSnippetFiles) {
        status.setText(`Uploading ${file.repoPath}...`);
        const content = await file.read();
        await gh.createFile(owner, rName, file.repoPath, content, `Add ${file.repoPath}`);
      }
      const screenshotFiles = this.getScreenshotFiles();
      const screenshotUrls = [...this.getExternalScreenshotUrls()];
      const readmeScreenshots = this.buildReadmeData().screenshots;
      for (const file of screenshotFiles) {
        status.setText(`Uploading ${file.repoPath}...`);
        const binary = await file.readBinary();
        await gh.createBinaryFile(owner, rName, file.repoPath, toBase64(binary), `Add ${file.repoPath}`);
        screenshotUrls.push(`https://raw.githubusercontent.com/${owner}/${rName}/HEAD/${file.repoPath}`);
      }
      const readmeContent = syncReadmeScreenshots(
        this.readmeContent || generateReadme(this.buildReadmeData()),
        readmeScreenshots
      );
      this.readmeContent = readmeContent;
      const finalScreenshotUrls = this.uniqueStrings([
        ...screenshotUrls,
        ...this.extractMarkdownImageUrls(readmeContent).map(
          (url) => this.resolvePublishedAssetUrl(owner, rName, url)
        )
      ]);
      status.setText("Generating hub.md...");
      const selectedPlugins = this.allPlugins.filter((p) => this.checkedPlugins.has(p.id)).map((p) => ({ ...p, autoDetected: true }));
      const obsVer = this.app.appVersion || "unknown";
      const themeName = ((_a = this.app.vault.config) == null ? void 0 : _a.cssTheme) || "default";
      const hubData = {
        type: publishedType,
        name: this.name,
        tagline: this.tagline,
        description: this.description,
        author: user.login,
        categories: this.categories,
        tags: this.tags.split(",").map((t) => t.trim()).filter(Boolean),
        compatibleThemes: this.compatibleThemes,
        screenshots: finalScreenshotUrls,
        plugins: selectedPlugins,
        attachedSnippets: attachedSnippetFiles.map((file) => ({
          path: file.repoPath,
          name: file.name,
          optional: file.optional
        })),
        obsidianVersion: obsVer,
        theme: themeName,
        os: navigator.platform,
        files: this.selectedFiles.map((f) => ({
          path: f.path,
          type: f.extension,
          size: f.size
        })),
        body: readmeContent
      };
      const hubMd = generateHubMd(hubData);
      await gh.createFile(owner, rName, "hub.md", hubMd, "Add hub.md");
      status.setText("Uploading README...");
      await gh.createFile(owner, rName, "README.md", readmeContent, "Add README");
      let refreshRequested = false;
      const catalogRepo = this.plugin.settings.catalogRepoFullName.trim();
      if (catalogRepo.includes("/")) {
        const [catalogOwner, catalogName] = catalogRepo.split("/");
        try {
          status.setText("Requesting catalog refresh...");
          await gh.dispatchRepositoryEvent(catalogOwner, catalogName, "catalog_refresh", {
            source_repo: repo.full_name,
            resource_type: publishedType
          });
          refreshRequested = true;
        } catch (e) {
          refreshRequested = false;
        }
      }
      this.plugin.settings.publishedResources.push({
        repoFullName: repo.full_name,
        localFilePath: this.selectedFiles[0].path,
        localFiles: this.selectedFiles.map((f) => f.path),
        fileMappings: [
          ...this.selectedFiles.map((f) => ({ localPath: f.path, repoPath: f.path, kind: "resource" })),
          ...attachedSnippetFiles.map((f) => ({ localPath: f.localPath, repoPath: f.repoPath, kind: "attached-snippet" })),
          ...screenshotFiles.map((f) => ({ localPath: f.localPath, repoPath: f.repoPath, kind: "screenshot" }))
        ],
        type: publishedType,
        lastPublishedAt: (/* @__PURE__ */ new Date()).toISOString()
      });
      this.plugin.settings.publishDraft = null;
      this.preserveDraftOnClose = false;
      await this.plugin.saveSettings();
      c.empty();
      c.createEl("h3", { text: "Published!" });
      c.createEl("p", { text: `Repository: ${repo.full_name}` });
      const vaultHubUrl = `https://obsidianvaulthub.com/r/${owner}/${rName}`;
      const actions = c.createDiv("vault-hub-success-actions");
      const link = actions.createEl("a", {
        text: "Open pending page on Vault Hub",
        href: vaultHubUrl,
        cls: "mod-cta vault-hub-success-link"
      });
      link.setAttr("target", "_blank");
      c.createEl("p", {
        text: refreshRequested ? "Catalog refresh requested. The listing should move from pending to indexed after the workflow finishes." : "Catalog refresh was not requested automatically. The listing may stay pending until the next scheduled refresh.",
        cls: "vault-hub-hint"
      });
      const ghLink = actions.createEl("a", {
        text: "View on GitHub",
        href: repo.html_url,
        cls: "vault-hub-hint"
      });
      ghLink.setAttr("target", "_blank");
      const closeBtn = actions.createEl("button", { text: "Close", cls: "mod-cta" });
      closeBtn.addEventListener("click", () => this.close());
      new import_obsidian2.Notice(`Published to ${repo.full_name}!`);
    } catch (e) {
      c.empty();
      c.createEl("h3", { text: "Error" });
      c.createEl("p", { text: String(e) });
      const retryBtn = c.createEl("button", { text: "Back to Review" });
      retryBtn.addEventListener("click", () => {
        this.step = 5;
        this.renderStep();
      });
    }
  }
  addNav(container, backCheck, nextCheck) {
    const nav = container.createDiv("vault-hub-nav");
    if (this.step > 1) {
      const back = nav.createEl("button", { text: "Back" });
      back.addEventListener("click", async () => {
        if (backCheck && !backCheck())
          return;
        this.step--;
        await this.saveDraft();
        this.renderStep();
      });
    }
    if (this.step < 5) {
      const next = nav.createEl("button", { text: "Next", cls: "mod-cta" });
      next.addEventListener("click", async () => {
        if (nextCheck && !nextCheck())
          return;
        this.step++;
        await this.saveDraft();
        this.renderStep();
      });
    }
  }
  buildReadmeData() {
    const selected = this.allPlugins.filter((plugin) => this.checkedPlugins.has(plugin.id)).map((plugin) => ({ ...plugin, autoDetected: true }));
    return {
      name: this.name,
      tagline: this.tagline,
      description: this.description,
      type: this.getPublishedType(),
      plugins: selected,
      files: this.selectedFiles.map((file) => ({ path: file.path })),
      attachedSnippets: this.getAttachedSnippetFiles().map((file) => ({
        path: file.repoPath,
        name: file.name,
        optional: file.optional
      })),
      screenshots: [
        ...this.getScreenshotFiles().map((file) => ({
          path: file.repoPath,
          alt: file.name
        })),
        ...this.getExternalScreenshotUrls().map((path, index) => ({
          path,
          alt: `Screenshot ${index + 1}`
        }))
      ]
    };
  }
  getAttachedSnippetFiles() {
    const used = /* @__PURE__ */ new Set();
    return this.selectedAttachedSnippets.map((file) => {
      const rawName = file.name.replace(/\.css$/i, "") || "snippet";
      let candidate = `${rawName}.css`;
      let suffix = 2;
      while (used.has(candidate.toLowerCase())) {
        candidate = `${rawName}-${suffix}.css`;
        suffix++;
      }
      used.add(candidate.toLowerCase());
      return {
        localPath: file.path,
        repoPath: `snippets/${candidate}`,
        name: rawName,
        read: file.read
      };
    });
  }
  getScreenshotFiles() {
    const used = /* @__PURE__ */ new Set();
    return this.selectedScreenshots.map((file) => {
      const dot = file.name.lastIndexOf(".");
      const stem = dot > 0 ? file.name.slice(0, dot) : file.name;
      const ext = dot > 0 ? file.name.slice(dot + 1).toLowerCase() : file.extension.toLowerCase();
      let candidate = `${stem}.${ext}`;
      let suffix = 2;
      while (used.has(candidate.toLowerCase())) {
        candidate = `${stem}-${suffix}.${ext}`;
        suffix++;
      }
      used.add(candidate.toLowerCase());
      return {
        localPath: file.path,
        repoPath: `screenshots/${candidate}`,
        name: stem,
        readBinary: file.readBinary || (async () => new ArrayBuffer(0))
      };
    });
  }
  getExternalScreenshotUrls() {
    return this.externalScreenshotUrls.split(/\r?\n/).map((line) => this.extractMarkdownUrl(line.trim())).filter(Boolean);
  }
  extractMarkdownUrl(value) {
    const imageMatch = value.match(/^!\[[^\]]*\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)$/);
    if (imageMatch)
      return imageMatch[1];
    const linkMatch = value.match(/^\[[^\]]+\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)$/);
    if (linkMatch)
      return linkMatch[1];
    return value.replace(/^["']|["']$/g, "");
  }
  extractMarkdownImageUrls(value) {
    const urls = [];
    const imagePattern = /!\[[^\]]*\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)/g;
    const screenshotLinkPattern = /\[([^\]]*screenshot[^\]]*)\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)/gi;
    let match;
    while (match = imagePattern.exec(value)) {
      urls.push(match[1]);
    }
    while (match = screenshotLinkPattern.exec(value)) {
      urls.push(match[2]);
    }
    return urls;
  }
  resolvePublishedAssetUrl(owner, repo, url) {
    if (/^(https?:|data:|blob:)/i.test(url))
      return url;
    const clean = url.replace(/^\.?\//, "").replace(/^blob\/[^/]+\//, "");
    return `https://raw.githubusercontent.com/${owner}/${repo}/HEAD/${clean}`;
  }
  uniqueStrings(values) {
    return values.filter((value, index, all) => value && all.indexOf(value) === index);
  }
};

// src/modals/UpdateModal.ts
var import_obsidian3 = require("obsidian");
var UpdateModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.selected = null;
    this.files = [];
    this.plugin = plugin;
  }
  onOpen() {
    this.renderSelect();
  }
  onClose() {
    this.contentEl.empty();
  }
  // ─── Step 1: select resource ───────────────────────────────
  renderSelect() {
    const c = this.contentEl;
    c.empty();
    c.addClass("vault-hub-modal");
    c.createEl("h2", { text: "Update Resource" });
    const resources = this.plugin.settings.publishedResources;
    if (resources.length === 0) {
      c.createEl("p", {
        text: "No published resources yet \u2014 publish one first.",
        cls: "vault-hub-hint"
      });
      return;
    }
    new import_obsidian3.Setting(c).setName("Resource").addDropdown((dd) => {
      dd.addOption("", "Select...");
      resources.forEach((r, i) => {
        dd.addOption(String(i), `${r.repoFullName} (${r.type}) \u2014 ${timeAgo(new Date(r.lastPublishedAt))}`);
      });
      dd.onChange((v) => {
        this.selected = v ? resources[parseInt(v)] : null;
      });
    });
    const btn = c.createEl("button", { text: "Check for Changes", cls: "mod-cta" });
    btn.style.marginTop = "12px";
    btn.addEventListener("click", async () => {
      if (!this.selected) {
        new import_obsidian3.Notice("Select a resource first");
        return;
      }
      if (!this.plugin.settings.githubToken) {
        new import_obsidian3.Notice("Set your GitHub token in settings");
        return;
      }
      await this.loadDiff(btn);
    });
  }
  // ─── Step 2: diff ─────────────────────────────────────────
  async loadDiff(triggerBtn) {
    triggerBtn.disabled = true;
    triggerBtn.setText("Checking...");
    const token = this.plugin.settings.githubToken;
    const [owner, repo] = this.selected.repoFullName.split("/");
    try {
      const gh = new GitHubAPI(token);
      const fileMappings = this.getFileMappings(this.selected);
      this.files = [];
      for (const mapping of fileMappings) {
        if (!mapping.localPath.match(/\.(md|css|yml|yaml|js|json|txt|canvas)$/i))
          continue;
        const entry = {
          name: mapping.repoPath,
          localPath: mapping.localPath,
          repoPath: mapping.repoPath,
          downloadUrl: "",
          status: "not-found"
        };
        const local = await this.readLocalContent(mapping.localPath);
        if (local !== null) {
          const remote = await gh.getFileContent(owner, repo, mapping.repoPath);
          entry.localContent = local;
          entry.githubSha = remote == null ? void 0 : remote.sha;
          entry.status = !remote || local !== remote.content ? "changed" : "unchanged";
        }
        this.files.push(entry);
      }
      this.renderDiff();
    } catch (e) {
      new import_obsidian3.Notice(`Error: ${e}`);
      triggerBtn.disabled = false;
      triggerBtn.setText("Check for Changes");
    }
  }
  renderDiff() {
    const c = this.contentEl;
    c.empty();
    c.createEl("h2", { text: "Review Changes" });
    c.createEl("p", { text: this.selected.repoFullName, cls: "vault-hub-hint" });
    const changed = this.files.filter((f) => f.status === "changed");
    const unchanged = this.files.filter((f) => f.status === "unchanged");
    const notFound = this.files.filter((f) => f.status === "not-found");
    const list = c.createDiv("vault-hub-update-list");
    changed.forEach((f) => {
      const row = list.createDiv("vault-hub-update-row");
      row.createSpan({ text: "~ ", cls: "vault-hub-status-changed" });
      row.createSpan({ text: f.name });
      row.createSpan({ text: " modified", cls: "vault-hub-hint" });
    });
    unchanged.forEach((f) => {
      const row = list.createDiv("vault-hub-update-row");
      row.createSpan({ text: "= ", cls: "vault-hub-status-unchanged" });
      row.createSpan({ text: f.name });
      row.createSpan({ text: " up to date", cls: "vault-hub-hint" });
    });
    notFound.forEach((f) => {
      const row = list.createDiv("vault-hub-update-row");
      row.createSpan({ text: "? ", cls: "vault-hub-status-missing" });
      row.createSpan({ text: f.name });
      row.createSpan({ text: " not found locally", cls: "vault-hub-hint" });
    });
    const nav = c.createDiv("vault-hub-nav");
    const backBtn = nav.createEl("button", { text: "Back" });
    backBtn.addEventListener("click", () => this.renderSelect());
    if (changed.length === 0) {
      c.createEl("p", { text: "Everything is up to date.", cls: "vault-hub-hint" });
    } else {
      const pushBtn = nav.createEl("button", {
        text: `Push ${changed.length} Change${changed.length !== 1 ? "s" : ""}`,
        cls: "mod-cta"
      });
      pushBtn.addEventListener("click", () => this.doPush(changed));
    }
  }
  // ─── Step 3: push ─────────────────────────────────────────
  async doPush(toUpdate) {
    const c = this.contentEl;
    c.empty();
    const statusEl = c.createEl("p", { text: "Pushing...", cls: "vault-hub-hint" });
    const token = this.plugin.settings.githubToken;
    const gh = new GitHubAPI(token);
    const [owner, repo] = this.selected.repoFullName.split("/");
    try {
      let pushed = 0;
      for (const f of toUpdate) {
        statusEl.setText(`Pushing ${f.name}...`);
        const existing = await gh.getFileContent(owner, repo, f.repoPath);
        if (existing) {
          await gh.updateFile(owner, repo, f.repoPath, f.localContent, `Update ${f.repoPath}`, existing.sha);
        } else {
          await gh.createFile(owner, repo, f.repoPath, f.localContent, `Add ${f.repoPath}`);
        }
        pushed++;
      }
      this.selected.lastPublishedAt = (/* @__PURE__ */ new Date()).toISOString();
      await this.plugin.saveSettings();
      let refreshRequested = false;
      const catalogRepo = this.plugin.settings.catalogRepoFullName.trim();
      if (catalogRepo.includes("/")) {
        const [catalogOwner, catalogName] = catalogRepo.split("/");
        try {
          await gh.dispatchRepositoryEvent(catalogOwner, catalogName, "catalog_refresh", {
            source_repo: this.selected.repoFullName,
            update: true
          });
          refreshRequested = true;
        } catch (e) {
          refreshRequested = false;
        }
      }
      c.empty();
      c.createEl("h3", { text: "Updated!" });
      c.createEl("p", { text: `Pushed ${pushed} file(s) to ${this.selected.repoFullName}` });
      c.createEl("p", {
        text: refreshRequested ? "Catalog refresh requested." : "Catalog refresh was not requested automatically.",
        cls: "vault-hub-hint"
      });
      const [rOwner, rName] = this.selected.repoFullName.split("/");
      const link = c.createEl("a", {
        text: "View on Vault Hub",
        href: `https://obsidianvaulthub.com/r/${rOwner}/${rName}`,
        cls: "mod-cta vault-hub-success-link"
      });
      link.setAttr("target", "_blank");
      const closeBtn = c.createEl("button", { text: "Close" });
      closeBtn.style.marginTop = "12px";
      closeBtn.addEventListener("click", () => this.close());
      new import_obsidian3.Notice(`Pushed ${pushed} file(s)!`);
    } catch (e) {
      c.empty();
      c.createEl("h3", { text: "Error" });
      c.createEl("p", { text: String(e) });
      const retryBtn = c.createEl("button", { text: "Back" });
      retryBtn.addEventListener("click", () => this.renderDiff());
    }
  }
  getFileMappings(resource) {
    var _a;
    if ((_a = resource.fileMappings) == null ? void 0 : _a.length)
      return resource.fileMappings;
    const localFiles = resource.localFiles || [resource.localFilePath];
    return localFiles.map((path) => ({
      localPath: path,
      repoPath: path,
      kind: "resource"
    }));
  }
  async readLocalContent(path) {
    const tfile = this.app.vault.getAbstractFileByPath(path);
    if (tfile instanceof import_obsidian3.TFile) {
      return this.app.vault.read(tfile);
    }
    try {
      if (await this.app.vault.adapter.exists(path)) {
        return await this.app.vault.adapter.read(path);
      }
    } catch (e) {
    }
    return null;
  }
};
function timeAgo(date) {
  const s = Math.floor((Date.now() - date.getTime()) / 1e3);
  if (s < 60)
    return "just now";
  const m = Math.floor(s / 60);
  if (m < 60)
    return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24)
    return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

// src/views/BrowseView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_BROWSE = "vault-hub-browse";
var TYPE_FILTERS = ["all", "vault", "snippet", "note", "dashboard"];
function normalizeToken(value) {
  return value.trim().toLowerCase().replace(/[\s_]+/g, "-");
}
function hasDashboardMarker(values) {
  return (values || []).some((value) => normalizeToken(value) === "dashboard");
}
function normalizeResource(resource) {
  const rawType = resource.rawType || resource.type;
  const subtype = rawType === "dashboard" || hasDashboardMarker(resource.categories) || hasDashboardMarker(resource.tags) ? "dashboard" : null;
  return {
    ...resource,
    rawType,
    type: rawType === "dashboard" ? "note" : rawType,
    subtype
  };
}
function getDisplayKind(resource) {
  return resource.subtype === "dashboard" ? "dashboard" : resource.type;
}
function isDashboardResource(resource) {
  return resource.subtype === "dashboard";
}
function encodeGitHubPath(path) {
  return path.split("/").map(encodeURIComponent).join("/");
}
function basename(path) {
  return path.split("/").pop() || path;
}
function extractFrontmatter(text) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
  return match ? match[1] : null;
}
function parseRequiredPluginIds(frontmatter) {
  const ids = [];
  let inPlugins = false;
  for (const line of frontmatter.split(/\r?\n/)) {
    if (/^plugins:\s*$/.test(line.trim())) {
      inPlugins = true;
      continue;
    }
    if (inPlugins && /^[A-Za-z0-9_-][^:]*:\s*/.test(line))
      break;
    if (!inPlugins)
      continue;
    const match = line.match(/^\s*-\s*id:\s*(.+)\s*$/);
    if (match)
      ids.push(match[1].trim().replace(/^["']|["']$/g, ""));
  }
  return ids;
}
function parseAttachedSnippets(frontmatter) {
  const snippets = [];
  let inAttachedSnippets = false;
  let current = null;
  const pushCurrent = () => {
    if (current == null ? void 0 : current.path)
      snippets.push(current);
    current = null;
  };
  for (const line of frontmatter.split(/\r?\n/)) {
    if (/^attached_snippets:\s*$/.test(line.trim())) {
      inAttachedSnippets = true;
      continue;
    }
    if (inAttachedSnippets && /^[A-Za-z0-9_-][^:]*:\s*/.test(line)) {
      pushCurrent();
      break;
    }
    if (!inAttachedSnippets)
      continue;
    const pathMatch = line.match(/^\s*-\s*path:\s*(.+)\s*$/);
    if (pathMatch) {
      pushCurrent();
      current = { path: pathMatch[1].trim().replace(/^["']|["']$/g, "") };
      continue;
    }
    const nameMatch = line.match(/^\s+name:\s*(.+)\s*$/);
    if (nameMatch && current) {
      current.name = nameMatch[1].trim().replace(/^["']|["']$/g, "");
      continue;
    }
    const optionalMatch = line.match(/^\s+optional:\s*(.+)\s*$/);
    if (optionalMatch && current) {
      current.optional = optionalMatch[1].trim().toLowerCase() === "true";
    }
  }
  pushCurrent();
  return snippets;
}
var BrowseView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.searchQuery = "";
    this.resources = [];
    this.activeTab = "browse";
    this.filterType = "all";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_BROWSE;
  }
  getDisplayText() {
    return "Vault Hub";
  }
  getIcon() {
    return "globe";
  }
  async onOpen() {
    this.render();
    await this.loadActiveTab();
  }
  async onClose() {
    this.contentEl.empty();
  }
  async loadActiveTab() {
    if (this.activeTab === "browse") {
      await this.loadResources();
    } else {
      await this.renderSnippetManager();
    }
  }
  render() {
    const c = this.contentEl;
    c.empty();
    c.addClass("vault-hub-browse");
    const tabBar = c.createDiv("vault-hub-tabs");
    ["browse", "snippets"].forEach((tab) => {
      const btn = tabBar.createEl("button", {
        text: tab === "browse" ? "Browse" : "Snippets",
        cls: `vault-hub-tab${this.activeTab === tab ? " active" : ""}`
      });
      btn.addEventListener("click", async () => {
        if (this.activeTab === tab)
          return;
        this.activeTab = tab;
        this.render();
        await this.loadActiveTab();
      });
    });
    if (this.activeTab === "browse") {
      const header = c.createDiv("vault-hub-browse-header");
      const searchRow = header.createDiv("vault-hub-search-row");
      const input = searchRow.createEl("input", {
        type: "text",
        placeholder: "Search resources..."
      });
      input.value = this.searchQuery;
      input.addEventListener("input", () => {
        this.searchQuery = input.value;
      });
      input.addEventListener("keydown", (e) => {
        if (e.key === "Enter")
          this.loadResources();
      });
      const searchBtn = searchRow.createEl("button", { text: "Search" });
      searchBtn.addEventListener("click", () => this.loadResources());
      const typeRow = c.createDiv("vault-hub-type-filters");
      TYPE_FILTERS.forEach((type) => {
        const btn = typeRow.createEl("button", {
          text: type === "all" ? "All" : type[0].toUpperCase() + type.slice(1),
          cls: `vault-hub-type-filter${this.filterType === type ? " active" : ""}`
        });
        if (type !== "all") {
          btn.dataset.type = type;
        }
        btn.addEventListener("click", async () => {
          this.filterType = type;
          typeRow.querySelectorAll(".vault-hub-type-filter").forEach((b) => b.removeClass("active"));
          btn.addClass("active");
          await this.loadResources();
        });
      });
      c.createDiv("vault-hub-results");
    } else {
      c.createDiv("vault-hub-snippets-container");
    }
  }
  // ─── BROWSE TAB ───────────────────────────────────────────────
  async loadResources() {
    const resultsEl = this.contentEl.querySelector(".vault-hub-results");
    if (!resultsEl)
      return;
    resultsEl.empty();
    resultsEl.createEl("p", { text: "Loading...", cls: "vault-hub-hint" });
    try {
      const limit = this.filterType === "dashboard" ? 100 : 30;
      const baseUrl = this.plugin.settings.vaultHubUrl.replace(/\/+$/, "");
      const params = new URLSearchParams({ limit: String(limit) });
      if (this.filterType !== "all") {
        params.set("type", this.filterType);
      }
      if (this.searchQuery.trim()) {
        params.set("q", this.searchQuery.trim());
      }
      const res = await fetch(`${baseUrl}/api/search?${params.toString()}`);
      const data = await res.json();
      if (!res.ok || !Array.isArray(data)) {
        throw new Error((data == null ? void 0 : data.error) || (data == null ? void 0 : data.message) || (data == null ? void 0 : data.hint) || "Unexpected response from API");
      }
      let resources = data.map(
        (resource) => normalizeResource(resource)
      );
      if (this.filterType === "dashboard") {
        resources = resources.filter((resource) => isDashboardResource(resource));
      }
      this.resources = resources;
      this.renderResults(resultsEl);
    } catch (e) {
      resultsEl.empty();
      resultsEl.createEl("p", { text: `Error: ${e}` });
    }
  }
  renderResults(container) {
    container.empty();
    if (this.resources.length === 0) {
      container.createEl("p", { text: "No resources found.", cls: "vault-hub-hint" });
      return;
    }
    const typeColors = {
      vault: "#7f6df2",
      snippet: "#22d3ee",
      note: "#fb923c",
      dashboard: "#4ade80"
    };
    this.resources.forEach((r) => {
      const displayKind = getDisplayKind(r);
      const card = container.createDiv("vault-hub-result-card");
      const badge = card.createSpan("vault-hub-type-badge");
      badge.setText(displayKind === "dashboard" ? "dashboard note" : r.type);
      badge.style.backgroundColor = typeColors[displayKind] || "#666";
      card.createEl("h4", { text: r.title });
      if (r.tagline) {
        card.createEl("p", { text: r.tagline, cls: "vault-hub-hint" });
      }
      const meta = card.createDiv("vault-hub-result-meta");
      meta.createSpan({ text: `${r.stars} stars` });
      meta.createSpan({ text: r.owner });
      const actions = card.createDiv("vault-hub-result-actions");
      const installBtn = actions.createEl("button", { text: "Install" });
      installBtn.addEventListener("click", () => this.installResource(r, installBtn));
      const ghBtn = actions.createEl("button", { text: "GitHub" });
      ghBtn.addEventListener("click", () => {
        window.open(`https://github.com/${r.full_name}`, "_blank");
      });
    });
  }
  // ─── INSTALL FLOWS ────────────────────────────────────────────
  async installResource(r, btn) {
    btn.disabled = true;
    btn.setText("Installing...");
    try {
      if (r.type === "vault") {
        await this.installVault(r);
      } else if (r.type === "snippet") {
        await this.installSnippet(r);
      } else {
        await this.installNotes(r);
      }
      btn.setText("Installed");
    } catch (e) {
      new import_obsidian4.Notice(`Install failed: ${e}`);
      btn.disabled = false;
      btn.setText("Install");
    }
  }
  /** Download full vault tree into a named subfolder */
  async installVault(r) {
    const treeRes = await fetch(
      `https://api.github.com/repos/${r.full_name}/git/trees/HEAD?recursive=1`,
      { headers: { Accept: "application/vnd.github.v3+json" } }
    );
    const treeData = await treeRes.json();
    if (!treeRes.ok || !Array.isArray(treeData.tree)) {
      throw new Error(treeData.message || "Failed to fetch repository tree");
    }
    const textExts = /\.(md|canvas|txt|css|js|ts|json|yaml|yml|html|xml|svg|toml|ini|cfg)$/i;
    const blobs = treeData.tree.filter(
      (item) => item.type === "blob" && !item.path.startsWith(".github/") && textExts.test(item.path)
    );
    const folderName = await this.availableFolder(r.repo_name);
    let installed = 0;
    let failed = 0;
    for (const item of blobs) {
      const destPath = `${folderName}/${item.path}`;
      const dirPath = destPath.split("/").slice(0, -1).join("/");
      await this.ensureDir(dirPath);
      const rawUrl = `https://raw.githubusercontent.com/${r.full_name}/HEAD/${encodeGitHubPath(item.path)}`;
      const raw = await fetch(rawUrl);
      if (!raw.ok) {
        failed++;
        continue;
      }
      await this.app.vault.adapter.write(destPath, await raw.text());
      installed++;
    }
    new import_obsidian4.Notice(
      `Installed "${r.title}" - ${installed} files in "${folderName}/"${failed ? ` (${failed} failed)` : ""}`
    );
    const hubMd = await this.fetchHubMd(r);
    if (hubMd) {
      await this.notifyRequiredPluginsFromContent(hubMd, r.title);
    }
  }
  async ensureDir(dirPath) {
    if (!dirPath)
      return;
    const parts = dirPath.split("/");
    let current = "";
    for (const part of parts) {
      current = current ? `${current}/${part}` : part;
      if (!await this.app.vault.adapter.exists(current)) {
        await this.app.vault.adapter.mkdir(current);
      }
    }
  }
  async availablePath(path) {
    if (!await this.app.vault.adapter.exists(path))
      return path;
    const slash = path.lastIndexOf("/");
    const dir = slash >= 0 ? path.slice(0, slash + 1) : "";
    const file = slash >= 0 ? path.slice(slash + 1) : path;
    const dot = file.lastIndexOf(".");
    const stem = dot > 0 ? file.slice(0, dot) : file;
    const ext = dot > 0 ? file.slice(dot) : "";
    let suffix = 2;
    let candidate = `${dir}${stem}-${suffix}${ext}`;
    while (await this.app.vault.adapter.exists(candidate)) {
      suffix++;
      candidate = `${dir}${stem}-${suffix}${ext}`;
    }
    return candidate;
  }
  async availableFolder(baseName) {
    let candidate = baseName;
    let suffix = 2;
    while (await this.app.vault.adapter.exists(candidate)) {
      candidate = `${baseName}-${suffix}`;
      suffix++;
    }
    return candidate;
  }
  async fetchHubMd(r) {
    const raw = await fetch(`https://raw.githubusercontent.com/${r.full_name}/HEAD/hub.md`);
    if (!raw.ok)
      return null;
    return raw.text();
  }
  async notifyRequiredPluginsFromContent(hubMd, title) {
    var _a;
    try {
      const frontmatter = extractFrontmatter(hubMd);
      if (!frontmatter)
        return;
      const ids = parseRequiredPluginIds(frontmatter);
      if (ids.length === 0)
        return;
      const installedPlugins = Object.keys(
        ((_a = this.app.plugins) == null ? void 0 : _a.plugins) || {}
      );
      const missing = ids.filter((id) => !installedPlugins.includes(id));
      if (missing.length === 0) {
        new import_obsidian4.Notice(`All required plugins already installed for "${title}"`);
      } else {
        new import_obsidian4.Notice(
          `"${title}" needs ${missing.length} plugin(s): ${missing.join(", ")}. Install from Community Plugins.`,
          1e4
        );
      }
    } catch (e) {
    }
  }
  /** Download CSS files to .obsidian/snippets/ */
  async installSnippet(r) {
    const treeRes = await fetch(
      `https://api.github.com/repos/${r.full_name}/git/trees/HEAD?recursive=1`,
      { headers: { Accept: "application/vnd.github.v3+json" } }
    );
    const treeData = await treeRes.json();
    if (!treeRes.ok || !Array.isArray(treeData.tree)) {
      throw new Error(treeData.message || "Failed to fetch repository tree");
    }
    const cssFiles = treeData.tree.filter(
      (f) => f.type === "blob" && f.path.endsWith(".css")
    );
    if (cssFiles.length === 0) {
      throw new Error("No CSS files found in this snippet repository");
    }
    const snippetsDir = `${this.app.vault.configDir}/snippets`;
    if (!await this.app.vault.adapter.exists(snippetsDir)) {
      await this.app.vault.adapter.mkdir(snippetsDir);
    }
    for (const f of cssFiles) {
      const raw = await fetch(`https://raw.githubusercontent.com/${r.full_name}/HEAD/${encodeGitHubPath(f.path)}`);
      if (!raw.ok)
        throw new Error(`Failed to download ${f.path}`);
      const target = await this.availablePath(`${snippetsDir}/${basename(f.path)}`);
      await this.app.vault.adapter.write(target, await raw.text());
    }
    new import_obsidian4.Notice(
      `Installed ${cssFiles.length} snippet(s) from "${r.title}" - enable in Settings \u2192 Appearance \u2192 CSS snippets`
    );
  }
  /** Download .md files into a named folder */
  async installNotes(r) {
    const hubMd = await this.fetchHubMd(r);
    const treeRes = await fetch(
      `https://api.github.com/repos/${r.full_name}/git/trees/HEAD?recursive=1`,
      { headers: { Accept: "application/vnd.github.v3+json" } }
    );
    const treeData = await treeRes.json();
    if (!treeRes.ok || !Array.isArray(treeData.tree)) {
      throw new Error(treeData.message || "Failed to fetch repository tree");
    }
    const mdFiles = treeData.tree.filter(
      (f) => f.type === "blob" && f.path.endsWith(".md") && basename(f.path).toLowerCase() !== "readme.md"
    );
    if (mdFiles.length === 0) {
      throw new Error("No note files found in this repository");
    }
    const folderName = await this.availableFolder(r.repo_name);
    let installed = 0;
    for (const f of mdFiles) {
      const raw = await fetch(`https://raw.githubusercontent.com/${r.full_name}/HEAD/${encodeGitHubPath(f.path)}`);
      if (!raw.ok)
        throw new Error(`Failed to download ${f.path}`);
      const destPath = `${folderName}/${f.path}`;
      await this.ensureDir(destPath.split("/").slice(0, -1).join("/"));
      await this.app.vault.adapter.write(destPath, await raw.text());
      installed++;
    }
    new import_obsidian4.Notice(`Installed ${installed} note(s) from "${r.title}" in "${folderName}/"`);
    if (hubMd) {
      await this.installAttachedSnippets(r, hubMd);
      await this.notifyRequiredPluginsFromContent(hubMd, r.title);
    }
  }
  async installAttachedSnippets(r, hubMd) {
    const frontmatter = extractFrontmatter(hubMd);
    if (!frontmatter)
      return;
    const attachedSnippets = parseAttachedSnippets(frontmatter);
    if (attachedSnippets.length === 0)
      return;
    const snippetsDir = `${this.app.vault.configDir}/snippets`;
    if (!await this.app.vault.adapter.exists(snippetsDir)) {
      await this.app.vault.adapter.mkdir(snippetsDir);
    }
    let installed = 0;
    let failed = 0;
    for (const snippet of attachedSnippets) {
      try {
        const raw = await fetch(
          `https://raw.githubusercontent.com/${r.full_name}/HEAD/${encodeGitHubPath(snippet.path)}`
        );
        if (!raw.ok) {
          failed++;
          continue;
        }
        const target = await this.availablePath(`${snippetsDir}/${basename(snippet.path)}`);
        await this.app.vault.adapter.write(target, await raw.text());
        installed++;
      } catch (e) {
        failed++;
      }
    }
    if (installed > 0 || failed > 0) {
      new import_obsidian4.Notice(
        `Installed ${installed} attached snippet(s) from "${r.title}"${failed ? ` (${failed} failed)` : ""}`
      );
    }
  }
  // ─── SNIPPET MANAGER ─────────────────────────────────────────
  async renderSnippetManager() {
    var _a;
    const container = this.contentEl.querySelector(".vault-hub-snippets-container");
    if (!container)
      return;
    container.empty();
    const snippetsDir = `${this.app.vault.configDir}/snippets`;
    let files = [];
    try {
      const listing = await this.app.vault.adapter.list(snippetsDir);
      files = listing.files.filter((f) => f.endsWith(".css")).map((f) => f.split("/").pop());
    } catch (e) {
      container.createEl("p", { text: "No snippets folder found.", cls: "vault-hub-hint" });
      return;
    }
    if (files.length === 0) {
      container.createEl("p", { text: "No snippets installed.", cls: "vault-hub-hint" });
      return;
    }
    let enabledSnippets = [];
    try {
      const raw = await this.app.vault.adapter.read(
        `${this.app.vault.configDir}/appearance.json`
      );
      enabledSnippets = ((_a = JSON.parse(raw)) == null ? void 0 : _a.enabledCssSnippets) || [];
    } catch (e) {
    }
    const list = container.createDiv("vault-hub-snippet-list");
    for (const fileName of files) {
      const snippetId = fileName.replace(/\.css$/, "");
      const isEnabled = enabledSnippets.includes(snippetId);
      const row = list.createDiv("vault-hub-snippet-row");
      row.createSpan({ text: snippetId, cls: "vault-hub-snippet-name" });
      const actions = row.createDiv("vault-hub-snippet-actions");
      const toggleBtn = actions.createEl("button", {
        text: isEnabled ? "Enabled" : "Disabled",
        cls: `vault-hub-snippet-toggle${isEnabled ? " on" : ""}`
      });
      toggleBtn.addEventListener("click", async () => {
        await this.setSnippetEnabled(snippetId, !isEnabled);
        await this.renderSnippetManager();
      });
      const deleteBtn = actions.createEl("button", {
        text: "Delete",
        cls: "vault-hub-snippet-delete"
      });
      deleteBtn.addEventListener("click", async () => {
        if (confirm(`Delete snippet "${snippetId}"?`)) {
          await this.app.vault.adapter.remove(`${snippetsDir}/${fileName}`);
          new import_obsidian4.Notice(`Deleted: ${snippetId}`);
          await this.renderSnippetManager();
        }
      });
    }
  }
  async setSnippetEnabled(snippetId, enable) {
    var _a, _b;
    const css = this.app.customCss;
    if (css) {
      if (css.setCssEnabledStatus) {
        css.setCssEnabledStatus(snippetId, enable);
        (_a = css.requestLoadSnippets) == null ? void 0 : _a.call(css);
        new import_obsidian4.Notice(`Snippet "${snippetId}" ${enable ? "enabled" : "disabled"}`);
        return;
      }
      if (css.enabledSnippets) {
        if (enable)
          css.enabledSnippets.add(snippetId);
        else
          css.enabledSnippets.delete(snippetId);
        (_b = css.requestLoadSnippets) == null ? void 0 : _b.call(css);
        new import_obsidian4.Notice(`Snippet "${snippetId}" ${enable ? "enabled" : "disabled"}`);
        return;
      }
    }
    try {
      const appearancePath = `${this.app.vault.configDir}/appearance.json`;
      let appearance = {};
      try {
        appearance = JSON.parse(await this.app.vault.adapter.read(appearancePath));
      } catch (e) {
      }
      const enabled = appearance.enabledCssSnippets || [];
      if (enable && !enabled.includes(snippetId)) {
        enabled.push(snippetId);
      } else if (!enable) {
        const i = enabled.indexOf(snippetId);
        if (i !== -1)
          enabled.splice(i, 1);
      }
      appearance.enabledCssSnippets = enabled;
      await this.app.vault.adapter.write(appearancePath, JSON.stringify(appearance, null, 2));
      new import_obsidian4.Notice(`Snippet "${snippetId}" ${enable ? "enabled" : "disabled"} - reload to apply`);
    } catch (e) {
      new import_obsidian4.Notice(`Failed to toggle snippet: ${e}`);
    }
  }
};

// src/main.ts
var VaultHubPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_BROWSE, (leaf) => new BrowseView(leaf, this));
    this.addCommand({
      id: "publish-resource",
      name: "Publish Resource",
      callback: () => new PublishModal(this.app, this).open()
    });
    this.addCommand({
      id: "update-resource",
      name: "Update Resource",
      callback: () => new UpdateModal(this.app, this).open()
    });
    this.addCommand({
      id: "browse-resources",
      name: "Browse Resources",
      callback: () => this.activateBrowseView()
    });
    this.addSettingTab(new VaultHubSettingTab(this.app, this));
    this.addRibbonIcon("globe", "Vault Hub", () => {
      this.activateBrowseView();
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateBrowseView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_BROWSE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_BROWSE, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
